version: "3.9"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
  web:
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/database
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    build: .
    command: uvicorn application:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/volume
    ports:
      - "8000:8000"
    depends_on:
      - db
